export const SET_VIEW = "SET_VIEW";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

export const ADD_LOCATION = "ADD_LOCATION";
export const SELECT_LOCATION = "SELECT_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION = "EDIT_LOCATION";
